# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_abbv', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=500)),
                ('participants', models.CharField(max_length=200)),
                ('speakers', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('price_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_alumni', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='venue_id',
            field=models.ForeignKey(blank=True, db_column='venue_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue', to='main.Venue'),
        ),
    ]
