# Generated by Django 2.2.6 on 2019-10-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_abbv', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('price_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_alumni', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('participants', models.CharField(blank=True, max_length=200)),
                ('speakers', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(blank=True)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('venue_id', models.ForeignKey(blank=True, db_column='venue_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='RentedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('equipment_id', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Equipment')),
                ('request_id', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Request')),
            ],
        ),
    ]
