# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='participants',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='purpose',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='speakers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='venue_id',
            field=models.ForeignKey(blank=True, db_column='venue_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Venue'),
        ),
    ]
