# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161010_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentsRented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Equipment')),
                ('request_id', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Request')),
            ],
        ),
    ]
