# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161010_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_needed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='time_needed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
