# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161011_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='time_needed',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='request',
            name='time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
