# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161011_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
