# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161011_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedequipment',
            name='unit',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
