# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161026_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_needed',
        ),
        migrations.RemoveField(
            model_name='request',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='request',
            name='time_to',
        ),
        migrations.AddField(
            model_name='requesteddate',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Request'),
        ),
    ]
