# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20161107_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osa_status', models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending')], max_length=8)),
                ('cdmo_status', models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending')], max_length=8)),
                ('cashier_status', models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending')], max_length=8)),
                ('ada_status', models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending')], max_length=8)),
                ('request_id', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Request')),
            ],
        ),
    ]
