# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_officestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officestatus',
            name='ada_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending'), ('AC', 'Active')], max_length=8),
        ),
        migrations.AlterField(
            model_name='officestatus',
            name='cashier_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending'), ('AC', 'Active')], max_length=8),
        ),
        migrations.AlterField(
            model_name='officestatus',
            name='cdmo_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending'), ('AC', 'Active')], max_length=8),
        ),
        migrations.AlterField(
            model_name='officestatus',
            name='osa_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending'), ('AC', 'Active')], max_length=8),
        ),
    ]
