# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20161113_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='remarks',
        ),
        migrations.AddField(
            model_name='officestatus',
            name='ada_remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='officestatus',
            name='cashier_remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='officestatus',
            name='cdmo_remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='officestatus',
            name='osa_remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
