# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_request_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
