# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20161128_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddate',
            name='time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesteddate',
            name='time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
