# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20161201_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddate',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesteddate',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
