# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20161201_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='venue',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
