# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20161208_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesteddate',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='requesteddate',
            old_name='start',
            new_name='start_date',
        ),
    ]
