# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20161208_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesteddate',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='requesteddate',
            name='start_date',
        ),
    ]
