# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20161208_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddate',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
